### ISSUE TITLE
the "x" format

### ISSUE THREAD

**Issue by astraw** [qtfkwk/dtg#1]
Hi, I noticed the "x" format looks interesting. Is it documented anywhere outside this package? It might be useful in the README and the docstrings to describe it a bit or to link some external documentation. Thanks!

**Comment by qtfkwk** [comment]
Hi, Andrew. Thanks for your interest. Not sure what you mean by "outside this package" (?)... I can tell you that I have not written any other documentation, blog post, white paper, etc about it. To be honest, I was just interested in having the shortest possible timestamp format where each character had some intelligible meaning and could be straight ASCII. Also, I'm not sure the algorithm is unique, but I am not aware of anyone using it aside from this utility.

What I have written up in the README (which appears at https://github.com/qtfkwk/dtg#usage but also over at https://crates.io/crates/dtg and https://docs.rs/crate/dtg) is pretty straightforward and appears in note 2:

```
    2. "x" format (base 60):

       0* 0 1 2 3 4 5 6 7 8 9
       1* A B C D E F G H I J
       2* K L M N O P Q R S T
       3* U V W X Y Z a b c d
       4* e f g h i j k l m n
       5* o p q r s t u v w x

       Field  | Values           | Result
       -------|------------------|----------
       Year   | 2020 => 33*60+40 | Xe
       Month  | Jan-Dec => 0-11  | 0-B
       Day    | 0-27/28/29/30    | 0-R/S/T/U
       Hour   | 0-23             | 0-N
       Minute | 0-59             | 0-x
       Second | 0-59             | 0-x
```

Further down in the README there are a few "x" format examples:

Get current date/time in "x" format:

```
$ dtg -x
XeAQ3LG
```

Get a specific date/time in "x" format:

```
$ dtg -x 1606447276.941324100
XeAQ3LG
```

Get a specific date / time from "x" format in RFC 3339 format:

```
$ dtg -X XeAQ3LG
2020-11-27T03:21:16Z
```

Do you have any specific questions you feel should/could be answered? Please let me know. Happy to help!

**Comment by astraw** [comment]
Thanks. Yes, I had seen your writeup. Beyond that, I had two further specific questions. I think the existing documentation would be further improved if you addressed them there.

* Is this format a custom format invented here? (Now I see "yes" - I was unsure of that previously - a search of the internet didn't turn up anything but search on "format x time" didn't necessarily seem to have a high signal-to-noise ratio.)
* Does the format deal with time zone? Is it defined only to be UTC, is it naive, or is the timezone encoded in it (I guess not)? Your last example makes it seem like it is defined to be UTC (`dtg -X XeAQ3LG` -> `2020-11-27T03:21:16Z`). Otherwise, the RFC 3339 conversion would not be correct because if it is naive, apparently RFC 3339 specifies the offset should be written as `-00:00`. But for now this might be accidental and it would be best to clarify before problems arise.

In any case, it looks like a nice micro format. I guess it has the nice property that (case-sensitive) alphabetical sorting will also be chronological sorting? Perhaps this would also be worth mentioning.

Thanks again.

**Comment by wyes-us** [comment]
Andrew, great points... am now thinking towards some improvements. To your second bullet, yes the "x" format time zone is always in UTC (enabling it to be used like epoch time / UNIX timestamp) and does not encode any time zone. I believe some additional examples would clarify converting "x" format timestamps to either the local or any other time zone:

Get a specific date / time from "x" format in the local timezone and default format:

```
$ dtg -X -l XeAQ3LG
Thu 26 Nov 2020 22:21:16 EST
```

Get a specific date / time from "x" format in explicit timezone and default format:

```
$ dtg -X -z MST XeAQ3LG
Thu 26 Nov 2020 20:21:16 MST
```

Get a specific date / time from "x" format in local timezone and specific format:

```
$ dtg -X -l -f %A XeAQ3LG
Thursday
XeAQ3LG
```

Get a specific date / time from "x" format in explicit timezone and specific format:

```
$ dtg -X -z MST -f %A XeAQ3LG
Thursday
XeAQ3LG
```

Finally, to your point on RFC 3339, the most relevant paragraph is at https://tools.ietf.org/html/rfc3339#section-4.3 :

> If the time in UTC is known, but the offset to local time is unknown, this can be represented with an offset of "-00:00".
> This differs semantically from an offset of "Z" or "+00:00", which imply that UTC is the preferred reference point for the specified time.

So for the "x" format, while the offset to local time is unknown, given that it is "always in UTC," so the second case is more accurate. A supporting note is that the `dtg` name itself stands for "date time group," which comes from military lexicon, and hence the preference towards `Z` / Zulu. The nearest way to convert to use an offset would be with `%z`:

```
$ dtg -X -z MST -f '%FT%T%z' XeAQ3LG
2021-04-29T05:14:14-0700
XeAQ3LG
```

**NOTE**: The last 3 examples uncovered a bug in the current version! It is not handling the `-X` and `-f` options correctly, and is appending the "x" format.

Updated roadmap (will knock out as soon as I'm able):

* [ ] Fix `-X` / `-f` conflict... possibly replace custom option handling with structopt, clap, ... (?)
* [ ] Add details for "x" format (novel afaik, UTC, ...) to README / CLI usage
* [ ] Add these examples to the README
* [ ] Add doc for strftime formats to README / CLI usage
* [ ] Add library interface (function, struct, ...) / API documentation

Thanks again for the discussion and helping make dtg better and more useful. Hopefully I've answered your questions; please let me know if not.

**Comment by qtfkwk** [comment]
Andrew, great points... am now thinking towards some improvements. To your second bullet, yes the "x" format time zone is always in UTC (enabling it to be used like epoch time / UNIX timestamp) and does not encode any time zone. I believe some additional examples would clarify converting "x" format timestamps to either the local or any other time zone:

Get a specific date / time from "x" format in the local timezone and default format:

```
$ dtg -X -l XeAQ3LG
Thu 26 Nov 2020 22:21:16 EST
```

Get a specific date / time from "x" format in explicit timezone and default format:

```
$ dtg -X -z MST XeAQ3LG
Thu 26 Nov 2020 20:21:16 MST
```

Get a specific date / time from "x" format in local timezone and specific format:

```
$ dtg -X -l -f %A XeAQ3LG
Thursday
XeAQ3LG
```

Get a specific date / time from "x" format in explicit timezone and specific format:

```
$ dtg -X -z MST -f %A XeAQ3LG
Thursday
XeAQ3LG
```

Finally, to your point on RFC 3339, the most relevant paragraph is at https://tools.ietf.org/html/rfc3339#section-4.3 :

> If the time in UTC is known, but the offset to local time is unknown, this can be represented with an offset of "-00:00".
> This differs semantically from an offset of "Z" or "+00:00", which imply that UTC is the preferred reference point for the specified time.

So for the "x" format, while the offset to local time is unknown, given that it is "always in UTC," so the second case is more accurate. A supporting note is that the `dtg` name itself stands for "date time group," which comes from military lexicon, and hence the preference towards `Z` / Zulu. The nearest way to convert to use an offset would be with `%z`:

```
$ dtg -X -z MST -f '%FT%T%z' XeAQ3LG
2021-04-29T05:14:14-0700
XeAQ3LG
```

**NOTE**: The last 3 examples uncovered a bug in the current version! It is not handling the `-X` and `-f` options correctly, and is appending the "x" format.

Updated roadmap (will knock out as soon as I'm able):

* [ ] Fix `-X` / `-f` conflict... possibly replace custom option handling with structopt, clap, ... (?)
* [ ] Add details for "x" format (novel afaik, UTC, ...) to README / CLI usage
* [ ] Add these examples to the README
* [ ] Add doc for strftime formats to README / CLI usage
* [ ] Add library interface (function, struct, ...) / API documentation

Thanks again for the discussion and helping make dtg better and more useful. Hopefully I've answered your questions; please let me know if not.

**Comment by astraw** [comment]
Thanks for the detailed write up. Due to inertia and human readability, for my use cases, I will probably continue to use files named like `20210429_172312.xyz` but this is a nice format to know about and, if it was widely adopted, seems like it might save the googles of the world money by having fewer bytes in email headers.

**Comment by qtfkwk** [comment]
Additional note on that `-X` / `-f` "bug"... actually it isn't really a bug, just a semi-surprising side effect using structopt struct field with a vec value. For instance, the `formats` option (`-f`) accepts one or more formats... well apparently these don't require repeated actual use of `-f`... e.g.: `dtg -f %A -f %b ...`. So, something like what we have above (`dtg -X -l -f %A XeAQ3LG`) is actually interpreting `XeAQ3LG` as a second format, not an argument, and giving today's day, which was accidentally correct on Thursday, but if I run it today, I see:

```
$ dtg -X -l -f %A XeAQ3LG
Saturday
XeAQ3LG
```

There are 2 immediate "fixes" (in the usage) that require no actual changes to the code: (a) use `--` to break between options and arguments, or (b) adjust option ordering to break up arguments to `-f` option.

a.

    ```
    $ dtg -X -l -f %A -- XeAQ3LG
    Thursday
    ```

b.

    ```
    $ dtg -f %A -X -l XeAQ3LG
    Thursday
    ```
